### PR TITLE
audio: rename audio buses to comply with original sources

### PR DESCRIPTION
**Pull request by rshym**
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>

### CODE REVIEW

**Comment by arminn** [comment]
Should we need to change car_audio_configuration.xml accordingly ?

**Comment by rshym** [comment]
Tested.
Built - OK.
No issues observed during run-time of built image.

**Comment by arminn** [comment]
Why you close that?

**Comment by rshym** [comment]
I think that this change has no impact on functionality.
I see that patch hanging for long time without actual need for it.
Also I'm not sure that we have to have same names as google has.
But if you think it's needed - I will reopen.

**Comment by rshym** [comment]
Reopened.

**Comment by arminn** [comment]
> I think that this change has no impact on functionality.

Actually, we have issues related to audio buses, and converting all to google like naming is a good start to solve them.

>I see that patch hanging for long time without actual need for it.

I've asked several times to do that task and from my understanding, it is the author's responsibility to pass the review.

>Also I'm not sure that we have to have same names as google has.

Please provide your point: why do we need to change google namings?

**Comment by rshym** [comment]
> Actually, we have issues related to audio buses, and converting all to google like naming is a good start to solve them.

Could you please provide some details regarding issue, so I can investigate it.

> I've asked several times to do that task and from my understanding, it is the author's responsibility to pass the review.

Correct. That patch was made on your request, was fixed and tested. And after that it hangs more than month without any attention from requestor. Obviously that there is no urgency in this change. So I, as author, decided to close it as not needed.

> Please provide your point: why do we need to change google namings?

I do not see need to prove that we need this change or we do not need this change. Reason of closure was that I see no interest from requestor. And from this discussion I see that patch is not approved, is not merged, but discussion is initiated. So if this PR is needed for discussions - I'm OK. Let's continue.

**Comment by arminn** [comment]
> Could you please provide some details regarding issue, so I can investigate it.

With enabled audioUseDynamicRouting there are errors/warnings related to bus routing.

> And after that it hangs more than month without any attention from requestor. 

This is absolutely not true. We disabled audioUseDynamicRouting and if I correctly understand - can't merge this patch without it. Since there is an issue with audio buses your statement "No issues observed during run-time" is a little bit wrong, since we have audio distortion and some warnings/errors during audioUseDynamicRouting enabled.


> Obviously that there is no urgency in this change. So I, as author, decided to close it as not needed.

The author is responsible for the change. And it is the responsibility of the author to get things done until the patch is merged.

> I do not see need to prove that we need this change or we do not need this change. 

Actually, you say "Also I'm not sure that we have to have the same names as google has." I guess you have some points?
I have a point why we need that and previously stated that. So please provide me yours.

>  And from this discussion I see that patch is not approved, is not merged, but discussion is initiated. 

Indeed, since we have audio issues with buses and routing how we merge that patch?

**Comment by rshym** [comment]
In overall, these statements looks like manipulation. You know that we disabled dynamic routing due to not implemented functionality in kernel and back-end.
And I doubt that change of human readable name will suddenly provide missing functionality.
What I see - is that we have strong desire to discuss from your side.

**Comment by arminn** [comment]
>You know that we disabled dynamic routing due to not implemented functionality in kernel and back-end.


I guess we disabled it due to issues with "sound distortion"? I'm not getting you point at all.

My logic was the following: if we have some issues with audio buses we should fix these issues and merge this patch with fixes. 

> And I doubt that change of human readable name will suddenly provide missing functionality.

No. But original config may be wrong.

**Comment by rshym** [comment]
I have checked setup with enabled dynamic routing, and can confirm sound distortions in some cases.
I made some investigation and below are my findings.
As far as we now use debug.stagefright.ccodec set to 0, we use other set of codecs, and they do not provide all functionality, required by higher level. I see that codecs do not support "set priority", and this affects upper level.
Also I see that distortions are observed only during playback of sound tracks marked as "navigation" or "VR". So only tracks that interact with other tracks (like decrease of volume of "media") results in distortion.
No distortion is observed during playback of clean "media" tracks, like music.
I strongly suspect that reason of distortion is some conflict between newer volume control (with dynamic) and older codecs.
For now that is result of my investigation.

**Comment by arminn** [comment]
> I see that codecs do not support "set priority", and this affects upper level.

It may be the cause of that issue.

I wonder do you see some warning logs regarding some specific audio buses when routing enabled?

**Comment by rshym** [comment]
Just checked fresh logs. I do not see any warnings or errors regarding audio buses. I searched for "bus", ".audio" and "looked over" logs.
Also I can hear clear sound without issues only for "media volume". All other "volume scrollbars" produce different distortions.

In logcat I can see
```
I GenericSource: start
I OMXClient: IOmx service obtained
I OMXMaster: makeComponentInstance(OMX.google.vorbis.decoder) in android.hardwar process
E OMXNodeInstance: setConfig(0xf07404e0:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
I ACodec  : codec does not support config priority (err -2147483648)
E OMXNodeInstance: getConfig(0xf07404e0:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
I MediaCodec: MediaCodec will operate in async mode
D xa_out  : out_write(0xe8540de0, buffer:0xe6f46040, bytes:8192)
```

**Comment by rshym** [comment]
Latest android was tested with this patch and without this patch.
No new issues were observed after application of patch.

Test environment:
- prod-devel DomA
- Android 11 with fixed memory usage
- Kingfisher

**Pull request merged**
