### PR TITLE
Switch emulated vehicle HAL by XT_USE_VIS_SERVER

### PR DESCRIPTION
**Pull request by rshym**
If XT_USE_VIS_SERVER is defined, we will use external
VIS server.
If XT_USE_VIS_SERVER is not defined - will use emulator.

### CODE REVIEW

**Comment by rshym** [comment]
Tested build of android with
a) export XT_USE_VIS_SERVER=true
```
rsm@pc2:/mnt/data1t/a11$ export XT_USE_VIS_SERVER=true
rsm@pc2:/mnt/data1t/a11$ m
device/xen/xenvm/build/device.mk:76: warning: External VIS server is used
```

b) export XT_USE_VIS_SERVER=
```
rsm@pc2:/mnt/data1t/a11$ m
device/xen/xenvm/build/device.mk:74: warning: VIS emulator is used
```

**Comment by arminn** [comment]
Reviewed-by: Andrii Chepurnyi andrii_chepurnyi@epam.com

**Review by arminn — APPROVED** [review]

**Comment by rshym** [comment]
Reviewer is added.
It's better to hold PR for some time, until patches on product will be finished and readme.md will be updated for android_manifest.

**Comment by rshym** [comment]
Corresponding update to readme: https://github.com/xen-troops/android_manifest/pull/61

**Comment by rshym** [comment]
Tested on prod-devel with REL 7.0 merged.
Works as expected.
Tested on two builds: with empty AOS_VIS_PLUGINS and with defined AOS_VIS_PLUGINS.

**Pull request merged**
